version: '3.7'
services:
  # frontend:
  backend:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: php.dockerfile
    image: pink-drive-be
    container_name: pink-drive-be-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app

  webserver:
    image: nginx:alpine
    container_name: pink-drive-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - app

  database:
    image: mysql:5.7
    container_name: pinkdrive-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    # ports:
    #  - "5000:3306"
    volumes:
      - ./db-volume:/var/lib/mysql
    networks:
      - app
networks:
  app:
    driver: bridge
